### PR TITLE
Add `System.Threading.Lock`

### PR DESCRIPTION
**Pull request by Tyrrrz**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
This lock class is not hardened against thread aborts coming from framework versions preceding .NET 5.0.

Consider using [Backport.System.Threading.Lock](https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock) instead of this method for locking, because it allows you to use the methods that the `System.Threading.Lock` class provides.

**Comment by Tyrrrz** [comment]
@MarkCiliaVincenti can you please elaborate on what you mean? I don't see substantial difference between this implementation and https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/c28041f1e22e561d5cde040704abeeb8d9a18649/Backport.System.Threading.Lock/Lock.cs#L15-L114

**Comment by MarkCiliaVincenti** [comment]
You're looking at the wrong file. Look at PreNet5Lock.cs and LockFactory.cs.

In fact I made that file you linked only available to net5 and upwards so if someone is on something lower they would not be able to use it.

**Comment by Tyrrrz** [comment]
> You're looking at the wrong file. Look at PreNet5Lock.cs and LockFactory.cs.
> 
> In fact I made that file you linked only available to net5 and upwards so if someone is on something lower they would not be able to use it.

I see now. I assume you're mainly referring to this part, right?

https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/c28041f1e22e561d5cde040704abeeb8d9a18649/Backport.System.Threading.Lock/PreNet5Lock.cs#L114-L124

**Comment by MarkCiliaVincenti** [comment]
No it's mainly the normal use case actually, locking on the object itself that is unsafe against thread aborts. It's why I needed the factory, so on frameworks before net9 they're given a return object that's on a different namespace.

**Comment by Tyrrrz** [comment]
You could've had them most in the same namespace though, right? Since these two types never appear at the same time.

**Comment by MarkCiliaVincenti** [comment]
The proper backport/polyfill is the one like yours. It's neat and all. Alas, evil thread aborts exists and these are locks we're talking about. Correctness is key in a library, but especially for locks because there exists a race condition of sorts whereby the lock of an aborted thread remains locked and no other threads can obtain the lock.

**Comment by Tyrrrz** [comment]
Yeah that's fair. I'll update the code on .NET FX to include the try/catch you have in your implementation and credit you in the comments. Thanks for the feedback!

**Comment by MarkCiliaVincenti** [comment]
Cool, but are you going to change the namespace? If you call it System.Threading.Lock, then you will still have problems.

**Comment by Tyrrrz** [comment]
Which problems are you referring to?

**Comment by MarkCiliaVincenti** [comment]
The main problem you have @Tyrrrz is that with your current code:

```csharp
private static readonly object _syncLock = new();

...

lock (_syncLock)
{
   doThis();
}
```

does not have the same behaviour as this on versions of .NET before .NET 5.0:

```csharp
private static readonly System.Threading.Lock _syncLock = new(); // this is from your polyfill

...

lock (_syncLock)
{
   doThis();
}
```

The object one gets lowered to this:

```csharp
bool lockTaken = false;
try
{
  Monitor.Enter(syncObject, ref lockTaken);
  doThis();
}
finally
{
  if (lockTaken)
  {
    Monitor.Exit(syncObject);
  }
}
```

but the polyfilled one **because it uses the System.Threading.Lock namespace** that's 'reserved' will get lowered to different code. Something like this:

```csharp
System.Threading.Lock.Scope scope = syncObject.EnterScope();
try
{
  doThis();
}
finally
{
  scope.Dispose();
}
```

In the above code, if the thread is aborted before it enters the try, i.e. right after obtaining the lock, it will never go into that finally and dispose cleanly, which means that it retains the lock and other threads would be unable to enter the lock as it would be left permanently locked for the lifetime of that lock instance.

**Comment by Tyrrrz** [comment]
But `syncObject.EnterScope()` already does `Monitor.Enter(syncObject, ref lockTaken)` as that's what it's meant to do in the polyfilled implementation.

**Comment by MarkCiliaVincenti** [comment]
I think the idea is to make the rudimentary lock work exactly like locking on an object would work pre net9. So yes it might work (though do check), but it still feels wrong. What if the lowering changes?

**Comment by MarkCiliaVincenti** [comment]
@Tyrrrz I confirmed it does call the `EnterScope`. Unfortunately when code gets lowered this way on < .NET 5.0, if the thread is aborted after the EnterScope and before entering the try, it will fail to dispose. This is not the case if you use a different namespace as I did in PreNet5Lock.cs. In a nutshell, you are still not hardened against thread aborts. Nothing using `EnterScope` is. This is why I had added this warning on the EnterScope method:

```csharp
[Obsolete("This method is a best-effort at hardening against thread aborts, but can theoretically retain lock on pre-.NET 5.0. Use with caution.")]
```

**Comment by MarkCiliaVincenti** [comment]
There's also another issue. If you create a .NET 8.0 library (let's call it 'ABC') that depends on this project, and then create a new .NET 9.0 project (let's call it 'DEF') that depends on 'ABC', you would get an error because DEF will get the .NET 9.0 version of your library (that would lack the `System.Threading.Lock`) and the library 'ABC' can't find the class it's meant to use.

My library solves this problem, because it is standalone targeting just `System.Threading.Lock`. It also solves the problem of thread aborts using a factory method.

Would you be willing to add a dependency to [this micro-library](https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock)?

**Comment by Tyrrrz** [comment]
> I think the idea is to make the rudimentary lock work exactly like locking on an object would work pre net9. So yes it might work (though do check), but it still feels wrong. What if the lowering changes?

Whichever way the lowering changes, it would still have to call `EnterScope(...)`, does it not?

> @Tyrrrz I confirmed it does call the `EnterScope`. Unfortunately when code gets lowered this way on < .NET 5.0, if the thread is aborted after the EnterScope and before entering the try, it will fail to dispose. This is not the case if you use a different namespace as I did in PreNet5Lock.cs. In a nutshell, you are still not hardened against thread aborts. Nothing using `EnterScope` is. This is why I had added this warning on the EnterScope method:
> 
> ```cs
> [Obsolete("This method is a best-effort at hardening against thread aborts, but can theoretically retain lock on pre-.NET 5.0. Use with caution.")]
> ```

Well, if the execution gets inside `EnterScope)` then this part that you wrote will take care of it:

https://github.com/Tyrrrz/PolyShim/blob/e56ec5ff0be4eb65d489301b5cfb1430aa5bb701/PolyShim/Net90/Lock.cs#L50-L56

It doesn't need `Dispose()` to be called.

Also, I cannot provide this type under a different namespace due to the nature of this project -- it contains polyfills which replace native types on frameworks that don't have them. Using the same namespace is imperative.


> There's also another issue. If you create a .NET 8.0 library (let's call it 'ABC') that depends on this project, and then create a new .NET 9.0 project (let's call it 'DEF') that depends on 'ABC', you would get an error because DEF will get the .NET 9.0 version of your library (that would lack the `System.Threading.Lock`) and the library 'ABC' can't find the class it's meant to use.
> 
> My library solves this problem, because it is standalone targeting just `System.Threading.Lock`. It also solves the problem of thread aborts using a factory method.
> 
> Would you be willing to add a dependency to [this micro-library](https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock)?

That would not happen because this library is not compiled. The polyfills are included as source code files and every single type provided is `internal`, so there aren't going to be any conflicts.

**Comment by Tyrrrz** [comment]
> If the thread is aborted after the EnterScope and before the try, which is absolutely possible, then the code as is will still retain the lock. The two processes are not atomic.

The thread is aborted after the `EnterScope()` but before the `try` then the lock will not be acquired in the first place since it's acquired within the `try`.

**Comment by MarkCiliaVincenti** [comment]
No it isn't. Look again. Not at my code, but at the code I said it would be inlined into. It first calls EnterScope outside of a try-finally, then goes into a try. If the thread is aborted inside the EnterScope or inside the try that happens after the EnterScope, you're safe. But there is still the theoretical race condition that it is aborted exactly after the EnterScope method returns.

**Comment by Tyrrrz** [comment]
Call trace:

```csharp
> System.Threading.Lock.Scope scope = syncObject.EnterScope();
try
{
  doThis();
}
finally
{
  scope.Dispose();
}
```

On .NET 9+ this resolves to some CLR calls.

On .NET 8 or lower this resolves to this:

```csharp
public Scope EnterScope()
{
>   var acquiredLock = false;
    try
    {
        Monitor.Enter(this, ref acquiredLock);
        return new Scope(this);
    }
    catch (ThreadAbortException)
    {
        if (acquiredLock)
            Monitor.Exit(this);

        throw;
    }
}
```

The lock is ever obtained when `Monitor.Enter(...)` is called, which is covered by a `try`/`catch`. The callsite will lead to this implementation due ot the polyfill.

**Comment by Tyrrrz** [comment]
`syncObject.EnterScope()` <- how is this implemented?

**Comment by Tyrrrz** [comment]
> It absolutely does NOT matter except that it returns a disposable object. A disposable object that is not disposed if an exception happens right after such object is returned.

But we know how it's implemented, because the implementation is provided by the polyfill on the versions of the framework where thread abortion matters.

Ultimately, like I said already, I can't claim a different namespace, it would defeat the purpose of the library. So if thread abortion is an issue, it'll have to be something I'll live with.



> My apologies Oleksii, a combination of me running high fever and talking about a subject I only recently found out about is resulting in me being unable to convey my point.

No problem, hope you feel better.

**Pull request merged**
